services:
  client:
    image: "brightly_client"
    environment:
      - MONGO_CONNECTION_STRING=${MONGO_CONNECTION_STRING}
    build:
      context: ./front
      dockerfile: ../Dockerfile-client
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./front


  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'

  server:
    image: "brightly_server"
    build:
      context: ./server
      dockerfile: ../Dockerfile-server
    depends_on:
      - "mongodb"
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: rebuild
          path: ./server